import sys
from pathlib import Path

backend_root = Path(__file__).resolve().parent
if str(backend_root) not in sys.path:
    sys.path.insert(0, str(backend_root))

from app.config.db import get_db_connection

def test_procedure():
    print("Testing DB connection...")
    conn = get_db_connection()
    if not conn:
        print("Failed to connect to the database!")
        return

    print("Connected successfully. Syncing identity sequence counter...")
    cursor = conn.cursor()
    try:
        cursor.execute("ALTER TABLE investments MODIFY (investment_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))")
        print("Identity sequence synced successfully.")
    except Exception as e:
        print("Sync failed (it might already be synced or failed for other reasons):", e)

    new_id = cursor.var(int)
    try:
        cursor.callproc(
            "add_asset_proc",
            [
                1,               # user_id
                "Test Bitcoin",  # asset_name
                "Crypto",        # asset_type
                3200.0,          # current_value
                18.0,            # growth_percentage
                new_id
            ]
        )
        print("Procedure called successfully! New ID:", new_id.getvalue())
        conn.commit()
    except Exception as e:
        print("EXCEPTION ENCOUNTERED:")
        import traceback
        traceback.print_exc()
    finally:
        cursor.close()
        conn.close()

if __name__ == "__main__":
    test_procedure()
