--------------------------------------------------------
-- Investment Procedure fixes and CRUD operations
-- Run this in Oracle after the main schema script.
--------------------------------------------------------
SET DEFINE OFF;

--------------------------------------------------------
-- Sync identity counter after imported explicit IDs
--------------------------------------------------------
ALTER TABLE investments
MODIFY investment_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

--------------------------------------------------------
-- 1. Portfolio Performance History (Chart Data)
--------------------------------------------------------
CREATE OR REPLACE PROCEDURE get_portfolio_history_proc (
    p_user_id   IN NUMBER,
    p_timeframe IN VARCHAR2,
    p_result    OUT SYS_REFCURSOR
) AS
        v_total_value NUMBER;
        v_days NUMBER;
    BEGIN
        -- Calculate sum of user's active assets
        SELECT NVL(SUM(current_value), 0)
        INTO v_total_value
        FROM investments
        WHERE user_id = p_user_id;

        -- If no assets exist, default to a baseline for rendering the chart structure
        IF v_total_value = 0 THEN
            v_total_value := 0;
        END IF;

        -- Map timeframe to number of historical data points (days)
        v_days := CASE UPPER(TRIM(p_timeframe))
            WHEN '1W' THEN 7
            WHEN '1M' THEN 30
            WHEN '1Y' THEN 365
            ELSE 7
        END;

        -- Dynamically generate historical dates and values to plot on the graph
        OPEN p_result FOR
            SELECT TO_CHAR(CURRENT_DATE - (v_days - LEVEL), 'YYYY-MM-DD HH24:MI:SS') AS record_date,
                v_total_value * (1 + (LEVEL - v_days) * 0.003 + SIN(LEVEL) * 0.01) AS portfolio_value
            FROM DUAL
            CONNECT BY LEVEL <= v_days
            ORDER BY LEVEL ASC;
    END;
    /

    --------------------------------------------------------
    -- 2. Retrieve all investments/assets for a user
    --------------------------------------------------------
    CREATE OR REPLACE PROCEDURE get_user_assets_proc (
        p_user_id IN NUMBER,
        p_result  OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_result FOR
            SELECT investment_id AS id,
                asset_name,
                asset_type,
                current_value,
                growth_percentage
            FROM investments
            WHERE user_id = p_user_id
            ORDER BY investment_id;
    END;
    /

    --------------------------------------------------------
    -- 3. Add a new investment asset
    --------------------------------------------------------
    CREATE OR REPLACE PROCEDURE add_asset_proc (
        p_user_id           IN  NUMBER,
        p_asset_name        IN  VARCHAR2,
        p_asset_type        IN  VARCHAR2,
        p_current_value     IN  NUMBER,
        p_growth_percentage IN  NUMBER,
        p_investment_id     OUT NUMBER
    ) AS
    BEGIN
        INSERT INTO investments
            (user_id, asset_name, asset_type, current_value, growth_percentage)
        VALUES
            (p_user_id, p_asset_name, p_asset_type, p_current_value, p_growth_percentage)
        RETURNING investment_id INTO p_investment_id;

        COMMIT;
    END;
    /

    --------------------------------------------------------
    -- 4. Update an existing investment asset
    --------------------------------------------------------
    CREATE OR REPLACE PROCEDURE update_asset_proc (
        p_id                IN  NUMBER,
        p_user_id           IN  NUMBER,
        p_asset_name        IN  VARCHAR2,
        p_asset_type        IN  VARCHAR2,
        p_current_value     IN  NUMBER,
        p_growth_percentage IN  NUMBER,
        p_rows_affected     OUT NUMBER
    ) AS
    BEGIN
        UPDATE investments
        SET asset_name = p_asset_name,
            asset_type = p_asset_type,
            current_value = p_current_value,
            growth_percentage = p_growth_percentage
        WHERE investment_id = p_id
        AND user_id = p_user_id;

        p_rows_affected := SQL%ROWCOUNT;
        COMMIT;
    END;
    /

    --------------------------------------------------------
    -- 5. Delete an investment asset
    --------------------------------------------------------
    CREATE OR REPLACE PROCEDURE delete_asset_proc (
        p_id            IN  NUMBER,
        p_user_id       IN  NUMBER,
        p_rows_affected OUT NUMBER
    ) AS
    BEGIN
        DELETE FROM investments
        WHERE investment_id = p_id
        AND user_id = p_user_id;

        p_rows_affected := SQL%ROWCOUNT;
        COMMIT;
    END;
    /
